jwt:
  issuer: tkddu1591@gmail.com
  secret: X5yicokSh8i94AxMdHb0pBp3BLY9NjOc
logging:
  file:
    name: log/HelloWorld.log
  level:
    jdbc:
      connection: info;
      resultsettable: info;
      sqlonly: info;
      sqltiming: info;
    org:
      hibernate: info;
      springframework:
        security: info;
    root: info
mybatis:
  mapper-locations: classpath:mappers/**/*.xml
server:
  servlet:
    context-path: /
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: tkddu1591@gmail.com
    password: krayblddzqwckqgq
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          auth-code-expiration-millis: 1800000  # 30 * 60 * 1000 == 30분
  jackson:
    serialization:
      write-dates-as-timestamps: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: ahffkdY1!
    url: jdbc:mysql://13.209.14.16:3306/HelloWorld?autoReconnect=true
    username: user1
  devtools:
    livereload:
      enabled: true
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
  thymeleaf:
    cache: false
    enabled : true
    prefix: classpath:/templates/
    suffix: .html
  servlet:
    multipart:
      location: thumbs/
      max-file-size: 10MB
file:
  dir: upload\
thumb:
  dir: thumbs\